from __future__ import annotations
from typing import Any
# Placeholders for SQLAlchemy models; real DB ops are not used in smoke path.
class Base: ...
class Experiment: ...
class Run: ...
class Metric: ...
class Artifact: ...
class RunExt: ...
